.TH "Src/EntityComponent/Components/Animator.cpp" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/EntityComponent/Components/Animator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Animator\&.h'\fP
.br
\fC#include 'EntityComponent/Entity\&.h'\fP
.br
\fC#include 'MeshRenderer\&.h'\fP
.br
\fC#include 'Render/RenderManager\&.h'\fP
.br
\fC#include <OgreAnimation\&.h>\fP
.br
\fC#include <OgreEntity\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
