.TH "Src/Input/Axis.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Input/Axis.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBme::AxisInfo\fP"
.br
.ti -1c
.RI "struct \fBme::Axis\fP"
.br
.ti -1c
.RI "struct \fBme::AxisInput\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__INPUT_AXIS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __INPUT_AXIS"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
