.TH "Src/Audio Directory Reference" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Audio Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSoundManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSoundManager\&.h\fP"
.br
.in -1c
