.TH "Src/EntityComponent/Components/Collider.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/EntityComponent/Components/Collider.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Component\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBme::Collider\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__EC_COLLIDER\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __EC_COLLIDER"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
