.TH "Src/EntityComponent/Components/Component.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/EntityComponent/Components/Component.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MotorEngine/MotorEngineAPI\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBme::Component\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__ENTITYCOMPONENT_COMPONENT\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __ENTITYCOMPONENT_COMPONENT"
This undefined class interface that is meant to be the root for any behavior designed as a component\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
