.TH "Src/MotorEngine/framework.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/MotorEngine/framework.h
.SH SYNOPSIS
.br
.PP
\fC#include <windows\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIN32_LEAN_AND_MEAN\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WIN32_LEAN_AND_MEAN"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
