.TH "Src/EntityComponent/InfoScene.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/EntityComponent/InfoScene.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <unordered_map>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::string \fBme::SceneName\fP"
.br
.ti -1c
.RI "typedef std::string \fBme::EntityName\fP"
.br
.ti -1c
.RI "typedef std::string \fBme::ComponentName\fP"
.br
.ti -1c
.RI "typedef std::string \fBme::ParameterName\fP"
.br
.ti -1c
.RI "typedef std::string \fBme::ParameterValue\fP"
.br
.ti -1c
.RI "typedef std::unordered_map< ParameterName, ParameterValue > \fBme::Parameters\fP"
.br
.ti -1c
.RI "typedef std::unordered_map< ComponentName, Parameters > \fBme::InfoEntity\fP"
.br
.ti -1c
.RI "typedef std::unordered_map< EntityName, InfoEntity > \fBme::InfoScene\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
