.TH "Src/Input/InputCode.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Input/InputCode.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MotorEngine/MotorEngineAPI\&.h'\fP
.br
\fC#include <SDL3/SDL_keyboard\&.h>\fP
.br
\fC#include <SDL3/SDL_mouse\&.h>\fP
.br
\fC#include <SDL3/SDL_gamepad\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__INPUT_INPUTCODE\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBINPUTTYPE_KEYBOARD\fP"
.br
.ti -1c
.RI "\fBINPUTTYPE_MOUSE_CLICK\fP"
.br
.ti -1c
.RI "\fBINPUTTYPE_MOUSE_MOTION\fP"
.br
.ti -1c
.RI "\fBINPUTTYPE_MOUSE_WHEEL\fP"
.br
.ti -1c
.RI "\fBINPUTTYPE_GAMEPAD_BUTTON\fP"
.br
.ti -1c
.RI "\fBINPUTTYPE_GAMEPAD_AXIS\fP"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_UNKNOWN\fP = SDLK_UNKNOWN"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_RETURN\fP = SDLK_RETURN"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_ESCAPE\fP = SDLK_ESCAPE"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_BACKSPACE\fP = SDLK_BACKSPACE"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_TAB\fP = SDLK_TAB"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_SPACE\fP = SDLK_SPACE"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_EXCLAIM\fP = SDLK_EXCLAIM"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_DOUBLEQUOTE\fP = SDLK_QUOTEDBL"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_HASH\fP = SDLK_HASH"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_PERCENT\fP = SDLK_PERCENT"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_DOLLAR\fP = SDLK_DOLLAR"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_AMPERSAND\fP = SDLK_AMPERSAND"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_QUOTE\fP = SDLK_QUOTE"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_LEFTPARENTHESIS\fP = SDLK_LEFTPAREN"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_RIGHTPARENTHESIS\fP = SDLK_RIGHTPAREN"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_ASTERISK\fP = SDLK_ASTERISK"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_PLUS\fP = SDLK_PLUS"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_COMMA\fP = SDLK_COMMA"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_MINUS\fP = SDLK_MINUS"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_PERIOD\fP = SDLK_PERIOD"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_SLASH\fP = SDLK_SLASH"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_0\fP = SDLK_0"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_1\fP = SDLK_1"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_2\fP = SDLK_2"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_3\fP = SDLK_3"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_4\fP = SDLK_4"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_5\fP = SDLK_5"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_6\fP = SDLK_6"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_7\fP = SDLK_7"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_8\fP = SDLK_8"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_9\fP = SDLK_9"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_COLON\fP = SDLK_COLON"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_SEMICOLON\fP = SDLK_SEMICOLON"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_LESS\fP = SDLK_LESS"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_EQUALS\fP = SDLK_EQUALS"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_GREATER\fP = SDLK_GREATER"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_QUESTION\fP = SDLK_QUESTION"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_AT\fP = SDLK_AT"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_LEFTBRACKET\fP = SDLK_LEFTBRACKET"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_BACKSLASH\fP = SDLK_BACKSLASH"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_RIGHTBRACKET\fP = SDLK_RIGHTBRACKET"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_CARET\fP = SDLK_CARET"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_UNDERSCORE\fP = SDLK_UNDERSCORE"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_BACKQUOTE\fP = SDLK_BACKQUOTE"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_A\fP = SDLK_a"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_B\fP = SDLK_b"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_C\fP = SDLK_c"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_D\fP = SDLK_d"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_E\fP = SDLK_e"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F\fP = SDLK_f"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_G\fP = SDLK_g"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_H\fP = SDLK_h"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_I\fP = SDLK_i"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_J\fP = SDLK_j"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_K\fP = SDLK_k"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_L\fP = SDLK_l"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_M\fP = SDLK_m"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_N\fP = SDLK_n"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_O\fP = SDLK_o"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_P\fP = SDLK_p"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_Q\fP = SDLK_q"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_R\fP = SDLK_r"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_S\fP = SDLK_s"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_T\fP = SDLK_t"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_U\fP = SDLK_u"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_V\fP = SDLK_v"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_W\fP = SDLK_w"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_X\fP = SDLK_x"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_Y\fP = SDLK_y"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_Z\fP = SDLK_z"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_CAPSLOCK\fP = SDLK_CAPSLOCK"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F1\fP = SDLK_F1"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F2\fP = SDLK_F2"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F3\fP = SDLK_F3"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F4\fP = SDLK_F4"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F5\fP = SDLK_F5"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F6\fP = SDLK_F6"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F7\fP = SDLK_F7"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F8\fP = SDLK_F8"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F9\fP = SDLK_F9"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F10\fP = SDLK_F10"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F11\fP = SDLK_F11"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_F12\fP = SDLK_F12"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_PRINTSCREEN\fP = SDLK_PRINTSCREEN"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_SCROLLLOCK\fP = SDLK_SCROLLLOCK"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_PAUSE\fP = SDLK_PAUSE"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_INSERT\fP = SDLK_INSERT"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_HOME\fP = SDLK_HOME"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_PAGEUP\fP = SDLK_PAGEUP"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_DELETE\fP = SDLK_DELETE"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_END\fP = SDLK_END"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_PAGEDOWN\fP = SDLK_PAGEDOWN"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_RIGHT\fP = SDLK_RIGHT"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_LEFT\fP = SDLK_LEFT"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_DOWN\fP = SDLK_DOWN"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_UP\fP = SDLK_UP"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_NUMLOCKCLEAR\fP = SDLK_NUMLOCKCLEAR"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_DIVIDE\fP = SDLK_KP_DIVIDE"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_MULTIPLY\fP = SDLK_KP_MULTIPLY"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_MINUS\fP = SDLK_KP_MINUS"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_PLUS\fP = SDLK_KP_PLUS"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_ENTER\fP = SDLK_KP_ENTER"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_1\fP = SDLK_KP_1"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_2\fP = SDLK_KP_2"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_3\fP = SDLK_KP_3"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_4\fP = SDLK_KP_4"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_5\fP = SDLK_KP_5"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_6\fP = SDLK_KP_6"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_7\fP = SDLK_KP_7"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_8\fP = SDLK_KP_8"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_9\fP = SDLK_KP_9"
.br
.ti -1c
.RI "\fBKEYBOARDCODE_NUMPAD_0\fP = SDLK_KP_0"
.br
.ti -1c
.RI "\fBMOUSE_LEFTCLICK\fP = SDL_BUTTON_LEFT"
.br
.ti -1c
.RI "\fBMOUSE_MIDDLECLICK\fP = SDL_BUTTON_MIDDLE"
.br
.ti -1c
.RI "\fBMOUSE_RIGHTCLICK\fP = SDL_BUTTON_RIGHT"
.br
.ti -1c
.RI "\fBMOUSE_X1\fP = SDL_BUTTON_X1"
.br
.ti -1c
.RI "\fBMOUSEWHEELCODE_NORMAL\fP = SDL_MOUSEWHEEL_NORMAL"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_INVALID\fP = SDL_GAMEPAD_BUTTON_INVALID"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_A\fP = SDL_GAMEPAD_BUTTON_A"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_B\fP = SDL_GAMEPAD_BUTTON_B"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_X\fP = SDL_GAMEPAD_BUTTON_X"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_Y\fP = SDL_GAMEPAD_BUTTON_Y"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_BACK\fP = SDL_GAMEPAD_BUTTON_BACK"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_GUIDE\fP = SDL_GAMEPAD_BUTTON_GUIDE"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_START\fP = SDL_GAMEPAD_BUTTON_START"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_LEFT_STICK\fP = SDL_GAMEPAD_BUTTON_LEFT_STICK"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_RIGHT_STICK\fP = SDL_GAMEPAD_BUTTON_RIGHT_STICK"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_LEFT_SHOULDER\fP = SDL_GAMEPAD_BUTTON_LEFT_SHOULDER"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_RIGHT_SHOULDER\fP = SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_DPAD_UP\fP = SDL_GAMEPAD_BUTTON_DPAD_UP"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_DPAD_DOWN\fP = SDL_GAMEPAD_BUTTON_DPAD_DOWN"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_DPAD_LEFT\fP = SDL_GAMEPAD_BUTTON_DPAD_LEFT"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_DPAD_RIGHT\fP = SDL_GAMEPAD_BUTTON_DPAD_RIGHT"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_MISC1\fP = SDL_GAMEPAD_BUTTON_MISC1"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_PADDLE1\fP = SDL_GAMEPAD_BUTTON_PADDLE1"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_PADDLE2\fP = SDL_GAMEPAD_BUTTON_PADDLE2"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_PADDLE3\fP = SDL_GAMEPAD_BUTTON_PADDLE3"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_PADDLE4\fP = SDL_GAMEPAD_BUTTON_PADDLE4"
.br
.ti -1c
.RI "\fBGAMEPAD_BUTTONCODE_TOUCHPAD\fP = SDL_GAMEPAD_BUTTON_TOUCHPAD"
.br
.ti -1c
.RI "\fBGAMEPAD_AXISCODE_INVALID\fP = SDL_GAMEPAD_AXIS_INVALID"
.br
.ti -1c
.RI "\fBGAMEPAD_AXISCODE_LEFTX\fP = SDL_GAMEPAD_AXIS_LEFTX"
.br
.ti -1c
.RI "\fBGAMEPAD_AXISCODE_LEFTY\fP = SDL_GAMEPAD_AXIS_LEFTY"
.br
.ti -1c
.RI "\fBGAMEPAD_AXISCODE_RIGHTX\fP = SDL_GAMEPAD_AXIS_RIGHTX"
.br
.ti -1c
.RI "\fBGAMEPAD_AXISCODE_RIGHTY\fP = SDL_GAMEPAD_AXIS_RIGHTY"
.br
.ti -1c
.RI "\fBGAMEPAD_AXISCODE_LEFT_TRIGGER\fP = SDL_GAMEPAD_AXIS_LEFT_TRIGGER"
.br
.ti -1c
.RI "\fBGAMEPAD_AXISCODE_RIGHT_TRIGGER\fP = SDL_GAMEPAD_AXIS_RIGHT_TRIGGER"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __INPUT_INPUTCODE"

.SH "Variable Documentation"
.PP 
.SS "GAMEPAD_AXISCODE_INVALID = SDL_GAMEPAD_AXIS_INVALID"

.SS "GAMEPAD_AXISCODE_LEFT_TRIGGER = SDL_GAMEPAD_AXIS_LEFT_TRIGGER"

.SS "GAMEPAD_AXISCODE_LEFTX = SDL_GAMEPAD_AXIS_LEFTX"

.SS "GAMEPAD_AXISCODE_LEFTY = SDL_GAMEPAD_AXIS_LEFTY"

.SS "GAMEPAD_AXISCODE_RIGHT_TRIGGER = SDL_GAMEPAD_AXIS_RIGHT_TRIGGER"

.SS "GAMEPAD_AXISCODE_RIGHTX = SDL_GAMEPAD_AXIS_RIGHTX"

.SS "GAMEPAD_AXISCODE_RIGHTY = SDL_GAMEPAD_AXIS_RIGHTY"

.SS "GAMEPAD_BUTTONCODE_A = SDL_GAMEPAD_BUTTON_A"

.SS "GAMEPAD_BUTTONCODE_B = SDL_GAMEPAD_BUTTON_B"

.SS "GAMEPAD_BUTTONCODE_BACK = SDL_GAMEPAD_BUTTON_BACK"

.SS "GAMEPAD_BUTTONCODE_DPAD_DOWN = SDL_GAMEPAD_BUTTON_DPAD_DOWN"

.SS "GAMEPAD_BUTTONCODE_DPAD_LEFT = SDL_GAMEPAD_BUTTON_DPAD_LEFT"

.SS "GAMEPAD_BUTTONCODE_DPAD_RIGHT = SDL_GAMEPAD_BUTTON_DPAD_RIGHT"

.SS "GAMEPAD_BUTTONCODE_DPAD_UP = SDL_GAMEPAD_BUTTON_DPAD_UP"

.SS "GAMEPAD_BUTTONCODE_GUIDE = SDL_GAMEPAD_BUTTON_GUIDE"

.SS "GAMEPAD_BUTTONCODE_INVALID = SDL_GAMEPAD_BUTTON_INVALID"

.SS "GAMEPAD_BUTTONCODE_LEFT_SHOULDER = SDL_GAMEPAD_BUTTON_LEFT_SHOULDER"

.SS "GAMEPAD_BUTTONCODE_LEFT_STICK = SDL_GAMEPAD_BUTTON_LEFT_STICK"

.SS "GAMEPAD_BUTTONCODE_MISC1 = SDL_GAMEPAD_BUTTON_MISC1"

.SS "GAMEPAD_BUTTONCODE_PADDLE1 = SDL_GAMEPAD_BUTTON_PADDLE1"

.SS "GAMEPAD_BUTTONCODE_PADDLE2 = SDL_GAMEPAD_BUTTON_PADDLE2"

.SS "GAMEPAD_BUTTONCODE_PADDLE3 = SDL_GAMEPAD_BUTTON_PADDLE3"

.SS "GAMEPAD_BUTTONCODE_PADDLE4 = SDL_GAMEPAD_BUTTON_PADDLE4"

.SS "GAMEPAD_BUTTONCODE_RIGHT_SHOULDER = SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER"

.SS "GAMEPAD_BUTTONCODE_RIGHT_STICK = SDL_GAMEPAD_BUTTON_RIGHT_STICK"

.SS "GAMEPAD_BUTTONCODE_START = SDL_GAMEPAD_BUTTON_START"

.SS "GAMEPAD_BUTTONCODE_TOUCHPAD = SDL_GAMEPAD_BUTTON_TOUCHPAD"

.SS "GAMEPAD_BUTTONCODE_X = SDL_GAMEPAD_BUTTON_X"

.SS "GAMEPAD_BUTTONCODE_Y = SDL_GAMEPAD_BUTTON_Y"

.SS "INPUTTYPE_GAMEPAD_AXIS"

.SS "INPUTTYPE_GAMEPAD_BUTTON"

.SS "INPUTTYPE_KEYBOARD"

.SS "INPUTTYPE_MOUSE_CLICK"

.SS "INPUTTYPE_MOUSE_MOTION"

.SS "INPUTTYPE_MOUSE_WHEEL"

.SS "KEYBOARDCODE_0 = SDLK_0"

.SS "KEYBOARDCODE_1 = SDLK_1"

.SS "KEYBOARDCODE_2 = SDLK_2"

.SS "KEYBOARDCODE_3 = SDLK_3"

.SS "KEYBOARDCODE_4 = SDLK_4"

.SS "KEYBOARDCODE_5 = SDLK_5"

.SS "KEYBOARDCODE_6 = SDLK_6"

.SS "KEYBOARDCODE_7 = SDLK_7"

.SS "KEYBOARDCODE_8 = SDLK_8"

.SS "KEYBOARDCODE_9 = SDLK_9"

.SS "KEYBOARDCODE_A = SDLK_a"

.SS "KEYBOARDCODE_AMPERSAND = SDLK_AMPERSAND"

.SS "KEYBOARDCODE_ASTERISK = SDLK_ASTERISK"

.SS "KEYBOARDCODE_AT = SDLK_AT"

.SS "KEYBOARDCODE_B = SDLK_b"

.SS "KEYBOARDCODE_BACKQUOTE = SDLK_BACKQUOTE"

.SS "KEYBOARDCODE_BACKSLASH = SDLK_BACKSLASH"

.SS "KEYBOARDCODE_BACKSPACE = SDLK_BACKSPACE"

.SS "KEYBOARDCODE_C = SDLK_c"

.SS "KEYBOARDCODE_CAPSLOCK = SDLK_CAPSLOCK"

.SS "KEYBOARDCODE_CARET = SDLK_CARET"

.SS "KEYBOARDCODE_COLON = SDLK_COLON"

.SS "KEYBOARDCODE_COMMA = SDLK_COMMA"

.SS "KEYBOARDCODE_D = SDLK_d"

.SS "KEYBOARDCODE_DELETE = SDLK_DELETE"

.SS "KEYBOARDCODE_DOLLAR = SDLK_DOLLAR"

.SS "KEYBOARDCODE_DOUBLEQUOTE = SDLK_QUOTEDBL"

.SS "KEYBOARDCODE_DOWN = SDLK_DOWN"

.SS "KEYBOARDCODE_E = SDLK_e"

.SS "KEYBOARDCODE_END = SDLK_END"

.SS "KEYBOARDCODE_EQUALS = SDLK_EQUALS"

.SS "KEYBOARDCODE_ESCAPE = SDLK_ESCAPE"

.SS "KEYBOARDCODE_EXCLAIM = SDLK_EXCLAIM"

.SS "KEYBOARDCODE_F = SDLK_f"

.SS "KEYBOARDCODE_F1 = SDLK_F1"

.SS "KEYBOARDCODE_F10 = SDLK_F10"

.SS "KEYBOARDCODE_F11 = SDLK_F11"

.SS "KEYBOARDCODE_F12 = SDLK_F12"

.SS "KEYBOARDCODE_F2 = SDLK_F2"

.SS "KEYBOARDCODE_F3 = SDLK_F3"

.SS "KEYBOARDCODE_F4 = SDLK_F4"

.SS "KEYBOARDCODE_F5 = SDLK_F5"

.SS "KEYBOARDCODE_F6 = SDLK_F6"

.SS "KEYBOARDCODE_F7 = SDLK_F7"

.SS "KEYBOARDCODE_F8 = SDLK_F8"

.SS "KEYBOARDCODE_F9 = SDLK_F9"

.SS "KEYBOARDCODE_G = SDLK_g"

.SS "KEYBOARDCODE_GREATER = SDLK_GREATER"

.SS "KEYBOARDCODE_H = SDLK_h"

.SS "KEYBOARDCODE_HASH = SDLK_HASH"

.SS "KEYBOARDCODE_HOME = SDLK_HOME"

.SS "KEYBOARDCODE_I = SDLK_i"

.SS "KEYBOARDCODE_INSERT = SDLK_INSERT"

.SS "KEYBOARDCODE_J = SDLK_j"

.SS "KEYBOARDCODE_K = SDLK_k"

.SS "KEYBOARDCODE_L = SDLK_l"

.SS "KEYBOARDCODE_LEFT = SDLK_LEFT"

.SS "KEYBOARDCODE_LEFTBRACKET = SDLK_LEFTBRACKET"

.SS "KEYBOARDCODE_LEFTPARENTHESIS = SDLK_LEFTPAREN"

.SS "KEYBOARDCODE_LESS = SDLK_LESS"

.SS "KEYBOARDCODE_M = SDLK_m"

.SS "KEYBOARDCODE_MINUS = SDLK_MINUS"

.SS "KEYBOARDCODE_N = SDLK_n"

.SS "KEYBOARDCODE_NUMPAD_0 = SDLK_KP_0"

.SS "KEYBOARDCODE_NUMPAD_1 = SDLK_KP_1"

.SS "KEYBOARDCODE_NUMPAD_2 = SDLK_KP_2"

.SS "KEYBOARDCODE_NUMPAD_3 = SDLK_KP_3"

.SS "KEYBOARDCODE_NUMPAD_4 = SDLK_KP_4"

.SS "KEYBOARDCODE_NUMPAD_5 = SDLK_KP_5"

.SS "KEYBOARDCODE_NUMPAD_6 = SDLK_KP_6"

.SS "KEYBOARDCODE_NUMPAD_7 = SDLK_KP_7"

.SS "KEYBOARDCODE_NUMPAD_8 = SDLK_KP_8"

.SS "KEYBOARDCODE_NUMPAD_9 = SDLK_KP_9"

.SS "KEYBOARDCODE_NUMPAD_DIVIDE = SDLK_KP_DIVIDE"

.SS "KEYBOARDCODE_NUMPAD_ENTER = SDLK_KP_ENTER"

.SS "KEYBOARDCODE_NUMPAD_MINUS = SDLK_KP_MINUS"

.SS "KEYBOARDCODE_NUMPAD_MULTIPLY = SDLK_KP_MULTIPLY"

.SS "KEYBOARDCODE_NUMPAD_NUMLOCKCLEAR = SDLK_NUMLOCKCLEAR"

.SS "KEYBOARDCODE_NUMPAD_PLUS = SDLK_KP_PLUS"

.SS "KEYBOARDCODE_O = SDLK_o"

.SS "KEYBOARDCODE_P = SDLK_p"

.SS "KEYBOARDCODE_PAGEDOWN = SDLK_PAGEDOWN"

.SS "KEYBOARDCODE_PAGEUP = SDLK_PAGEUP"

.SS "KEYBOARDCODE_PAUSE = SDLK_PAUSE"

.SS "KEYBOARDCODE_PERCENT = SDLK_PERCENT"

.SS "KEYBOARDCODE_PERIOD = SDLK_PERIOD"

.SS "KEYBOARDCODE_PLUS = SDLK_PLUS"

.SS "KEYBOARDCODE_PRINTSCREEN = SDLK_PRINTSCREEN"

.SS "KEYBOARDCODE_Q = SDLK_q"

.SS "KEYBOARDCODE_QUESTION = SDLK_QUESTION"

.SS "KEYBOARDCODE_QUOTE = SDLK_QUOTE"

.SS "KEYBOARDCODE_R = SDLK_r"

.SS "KEYBOARDCODE_RETURN = SDLK_RETURN"

.SS "KEYBOARDCODE_RIGHT = SDLK_RIGHT"

.SS "KEYBOARDCODE_RIGHTBRACKET = SDLK_RIGHTBRACKET"

.SS "KEYBOARDCODE_RIGHTPARENTHESIS = SDLK_RIGHTPAREN"

.SS "KEYBOARDCODE_S = SDLK_s"

.SS "KEYBOARDCODE_SCROLLLOCK = SDLK_SCROLLLOCK"

.SS "KEYBOARDCODE_SEMICOLON = SDLK_SEMICOLON"

.SS "KEYBOARDCODE_SLASH = SDLK_SLASH"

.SS "KEYBOARDCODE_SPACE = SDLK_SPACE"

.SS "KEYBOARDCODE_T = SDLK_t"

.SS "KEYBOARDCODE_TAB = SDLK_TAB"

.SS "KEYBOARDCODE_U = SDLK_u"

.SS "KEYBOARDCODE_UNDERSCORE = SDLK_UNDERSCORE"

.SS "KEYBOARDCODE_UNKNOWN = SDLK_UNKNOWN"

.SS "KEYBOARDCODE_UP = SDLK_UP"

.SS "KEYBOARDCODE_V = SDLK_v"

.SS "KEYBOARDCODE_W = SDLK_w"

.SS "KEYBOARDCODE_X = SDLK_x"

.SS "KEYBOARDCODE_Y = SDLK_y"

.SS "KEYBOARDCODE_Z = SDLK_z"

.SS "MOUSE_LEFTCLICK = SDL_BUTTON_LEFT"

.SS "MOUSE_MIDDLECLICK = SDL_BUTTON_MIDDLE"

.SS "MOUSE_RIGHTCLICK = SDL_BUTTON_RIGHT"

.SS "MOUSE_X1 = SDL_BUTTON_X1"

.SS "MOUSEWHEELCODE_NORMAL = SDL_MOUSEWHEEL_NORMAL"
The scroll direction is normal 
.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
