.TH "Src/Input/InputManager.cpp" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Input/InputManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'InputManager\&.h'\fP
.br
\fC#include 'InputCode\&.h'\fP
.br
\fC#include <SDL3/SDL_events\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEVENT_BUTTON_DOWN\fP"
.br
.ti -1c
.RI "#define \fBEVENT_BUTTON_UP\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EVENT_BUTTON_DOWN"
\fBValue:\fP.PP
.nf
    event\->type == SDL_EVENT_KEY_DOWN || \\
    event\->type == SDL_EVENT_MOUSE_BUTTON_DOWN || \\
    event\->type == SDL_EVENT_GAMEPAD_BUTTON_DOWN
.fi

.SS "#define EVENT_BUTTON_UP"
\fBValue:\fP.PP
.nf
    event\->type == SDL_EVENT_KEY_UP || \\
    event\->type == SDL_EVENT_MOUSE_BUTTON_UP || \\
    event\->type == SDL_EVENT_GAMEPAD_BUTTON_UP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
