.TH "me::AxisInput" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::AxisInput
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Axis\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InputType \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int \fBwhich\fP"
.br
.ti -1c
.RI "   int \fBpositive\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "int \fBnegative\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "union  { \&.\&.\&. }  me::AxisInput::@2"

.SS "int me::AxisInput::negative"

.SS "int me::AxisInput::positive"

.SS "InputType me::AxisInput::type"

.SS "int me::AxisInput::which"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
