.TH "me::Axis" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::Axis
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Axis\&.h>\fP
.PP
Inherits \fBme::AxisInfo\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBactive\fP"
.br
.in -1c

Public Attributes inherited from \fBme::AxisInfo\fP
.in +1c
.ti -1c
.RI "float \fBgravity\fP"
.br
.ti -1c
.RI "float \fBdead\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Representation of a virtual axis, so you can unify input given any controller, keyboard or mouse 
.SH "Member Data Documentation"
.PP 
.SS "bool me::Axis::active"

.SS "float me::Axis::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
