.TH "me::Animator" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::Animator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Animator\&.h>\fP
.PP
Inherits \fBme::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimator\fP ()"
.br
.ti -1c
.RI "\fB~Animator\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP () override"
.br
.ti -1c
.RI "void \fBsetActive\fP (bool state)"
.br
.ti -1c
.RI "void \fBsetLoop\fP (bool state)"
.br
.ti -1c
.RI "std::string \fBgetCurrAnimName\fP ()"
.br
.ti -1c
.RI "bool \fBisActive\fP ()"
.br
.ti -1c
.RI "bool \fBisLoop\fP ()"
.br
.ti -1c
.RI "bool \fBanimHasEnded\fP ()"
.br
.ti -1c
.RI "void \fBplayAnim\fP (std::string anim, bool loop=true)"
.br
.ti -1c
.RI "void \fBstopAnim\fP ()"
.br
.ti -1c
.RI "void \fBresumeAnim\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBme::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP ()"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()"
.br
.ti -1c
.RI "void \fBsetEntity\fP (\fBEntity\fP *e)"
.br
.ti -1c
.RI "\fBEntity\fP * \fBgetEntity\fP ()"
.br
.ti -1c
.RI "virtual void \fBstart\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBlateUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnCollisionEnter\fP (\fBEntity\fP *other)"
.br
.ti -1c
.RI "virtual void \fBOnCollisionStay\fP (\fBEntity\fP *other)"
.br
.ti -1c
.RI "virtual void \fBOnCollisionExit\fP (\fBEntity\fP *other)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBme::Component\fP
.in +1c
.ti -1c
.RI "bool \fBenabled\fP = true"
.br
.in -1c

Protected Attributes inherited from \fBme::Component\fP
.in +1c
.ti -1c
.RI "\fBEntity\fP * \fBmEntity\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Animator::Animator ()"

.SS "Animator::~Animator ()"

.SH "Member Function Documentation"
.PP 
.SS "bool Animator::animHasEnded ()"

.SS "std::string Animator::getCurrAnimName ()"
Returns the name of the current animation being played 
.PP
\fBReturns\fP
.RS 4
A string containing the name of the current animation 
.RE
.PP

.SS "bool Animator::isActive ()"
Returns the \fBAnimator\fP's active state 
.PP
\fBReturns\fP
.RS 4
A boolean value indicating whether the \fBAnimator\fP is active or not 
.RE
.PP

.SS "bool Animator::isLoop ()"
Returns the \fBAnimator\fP's loop state 
.PP
\fBReturns\fP
.RS 4
A boolean value indicating whether the current animation should loop or not 
.RE
.PP

.SS "void Animator::playAnim (std::string anim, bool loop = \fCtrue\fP)"
Plays a specified animation on the \fBEntity\fP 
.PP
\fBParameters\fP
.RS 4
\fIanim\fP A string containing the name of the animation to be played 
.br
\fIloop\fP A boolean value indicating whether the animation should loop or not 
.RE
.PP

.SS "void Animator::resumeAnim ()"
Resumes the current animation 
.SS "void Animator::setActive (bool state)"
Sets the \fBAnimator\fP's active state 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP Boolean value indicating whether the \fBAnimator\fP should be active or not 
.RE
.PP

.SS "void Animator::setLoop (bool state)"
Sets the \fBAnimator\fP's loop state 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP Boolean value indicating whether the current animation should loop or not 
.RE
.PP

.SS "void Animator::stopAnim ()"
Stops the current animation 
.SS "void Animator::update ()\fC [override]\fP, \fC [virtual]\fP"
This method is meant to be the definition of those updates that has to be processed at the begining of the game cycle\&.
.PP
Almost all the logic updates\&. 
.PP
Reimplemented from \fBme::Component\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
