.TH "me::Button" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::Button
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Button\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBpressed\fP"
.br
.ti -1c
.RI "int \fBplayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Representation of a virtual button, so you can unify input given any controller, keyboard or mouse\&. 
.SH "Member Data Documentation"
.PP 
.SS "int me::Button::player"

.SS "bool me::Button::pressed"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
