.TH "me::Collider" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::Collider
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Collider\&.h>\fP
.PP
Inherits \fBme::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollider\fP ()"
.br
.ti -1c
.RI "virtual \fB~Collider\fP ()"
.br
.ti -1c
.RI "void \fBonCollisionEnter\fP (\fBEntity\fP *other)"
.br
.ti -1c
.RI "void \fBonCollisionStay\fP (\fBEntity\fP *other)"
.br
.ti -1c
.RI "void \fBonCollisionExit\fP (\fBEntity\fP *other)"
.br
.in -1c

Public Member Functions inherited from \fBme::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP ()"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()"
.br
.ti -1c
.RI "void \fBsetEntity\fP (\fBEntity\fP *e)"
.br
.ti -1c
.RI "\fBEntity\fP * \fBgetEntity\fP ()"
.br
.ti -1c
.RI "virtual void \fBstart\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBlateUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnCollisionEnter\fP (\fBEntity\fP *other)"
.br
.ti -1c
.RI "virtual void \fBOnCollisionStay\fP (\fBEntity\fP *other)"
.br
.ti -1c
.RI "virtual void \fBOnCollisionExit\fP (\fBEntity\fP *other)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBme::Component\fP
.in +1c
.ti -1c
.RI "bool \fBenabled\fP = true"
.br
.in -1c

Protected Attributes inherited from \fBme::Component\fP
.in +1c
.ti -1c
.RI "\fBEntity\fP * \fBmEntity\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "me::Collider::Collider ()"

.SS "me::Collider::~Collider ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void me::Collider::onCollisionEnter (\fBEntity\fP * other)"
Set the entity activity to the boolean petition\&. 
.PP
\fBParameters\fP
.RS 4
\fIBoolean\fP state activity\&. 
.RE
.PP

.SS "void me::Collider::onCollisionExit (\fBEntity\fP * other)"
Set the entity activity to the boolean petition\&. 
.PP
\fBParameters\fP
.RS 4
\fIBoolean\fP state activity\&. 
.RE
.PP

.SS "void me::Collider::onCollisionStay (\fBEntity\fP * other)"
Set the entity activity to the boolean petition\&. 
.PP
\fBParameters\fP
.RS 4
\fIBoolean\fP state activity\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
