.TH "me::Camera" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::Camera
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Camera\&.h>\fP
.PP
Inherits \fBme::Component\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP ()"
.br
.ti -1c
.RI "\fB~Camera\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string name)"
.br
.ti -1c
.RI "void \fBsetNearDistance\fP (int nearDistance)"
.br
.ti -1c
.RI "void \fBsetFarDistance\fP (int farDistance)"
.br
.ti -1c
.RI "void \fBsetAutoRadio\fP (bool autoRadio)"
.br
.ti -1c
.RI "void \fBsetZOrder\fP (int zOrder)"
.br
.ti -1c
.RI "void \fBsetLookAt\fP (\fBVector3\fP lookAt)"
.br
.ti -1c
.RI "void \fBstart\fP () override"
.br
.ti -1c
.RI "void \fBupdate\fP () override"
.br
.ti -1c
.RI "void \fBsetStatic\fP (bool stat)"
.br
.ti -1c
.RI "void \fBsetViewportDimension\fP (float left, float top, float width, float height)"
.br
.in -1c

Public Member Functions inherited from \fBme::Component\fP
.in +1c
.ti -1c
.RI "\fBComponent\fP ()"
.br
.ti -1c
.RI "virtual \fB~Component\fP ()"
.br
.ti -1c
.RI "void \fBsetEntity\fP (\fBEntity\fP *e)"
.br
.ti -1c
.RI "\fBEntity\fP * \fBgetEntity\fP ()"
.br
.ti -1c
.RI "virtual void \fBstart\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBlateUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnCollisionEnter\fP (\fBEntity\fP *other)"
.br
.ti -1c
.RI "virtual void \fBOnCollisionStay\fP (\fBEntity\fP *other)"
.br
.ti -1c
.RI "virtual void \fBOnCollisionExit\fP (\fBEntity\fP *other)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmName\fP"
.br
.ti -1c
.RI "int \fBmNearDistance\fP"
.br
.ti -1c
.RI "int \fBmFarDistance\fP"
.br
.ti -1c
.RI "bool \fBmAutoRadio\fP"
.br
.ti -1c
.RI "int \fBmZOrder\fP"
.br
.ti -1c
.RI "\fBVector3\fP \fBmLookAt\fP"
.br
.ti -1c
.RI "\fBTransform\fP * \fBmTransform\fP"
.br
.ti -1c
.RI "bool \fBmStaticObject\fP = true"
.br
.in -1c

Protected Attributes inherited from \fBme::Component\fP
.in +1c
.ti -1c
.RI "\fBEntity\fP * \fBmEntity\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBme::Component\fP
.in +1c
.ti -1c
.RI "bool \fBenabled\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBCamera\fP class create camera(Viewer) in scene 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "me::Camera::Camera ()"

.SS "me::Camera::~Camera ()"

.SH "Member Function Documentation"
.PP 
.SS "void me::Camera::setAutoRadio (bool autoRadio)\fC [inline]\fP"

.SS "void me::Camera::setFarDistance (int farDistance)\fC [inline]\fP"

.SS "void me::Camera::setLookAt (\fBVector3\fP lookAt)\fC [inline]\fP"

.SS "void me::Camera::setName (std::string name)\fC [inline]\fP"

.SS "void me::Camera::setNearDistance (int nearDistance)\fC [inline]\fP"

.SS "void me::Camera::setStatic (bool stat)"
Set it is static entity or not 
.SS "void me::Camera::setViewportDimension (float left, float top, float width, float height)"
Set dimension to the viewport of the camera with this name 
.PP
\fBParameters\fP
.RS 4
\fIname\fP name of camera 
.br
\fIleft\fP left point of viewport in range 0\&.0 to 1\&.0 
.br
\fItop\fP top point of viewport in range 0\&.0 to 1\&.0 
.br
\fIwidth\fP width of viewport in range 0\&.0 to 1\&.0 
.br
\fIheight\fP height of viewport in range 0\&.0 to 1\&.0 
.RE
.PP
\fBReturns\fP
.RS 4
false: if it doesn't exist 
.PP
true: if succeed 
.RE
.PP

.SS "void me::Camera::setZOrder (int zOrder)\fC [inline]\fP"

.SS "void me::Camera::start ()\fC [override]\fP, \fC [virtual]\fP"
Get info for mTransform and create ogreCamera and set the start pos 
.PP
Reimplemented from \fBme::Component\fP\&.
.SS "void me::Camera::update ()\fC [override]\fP, \fC [virtual]\fP"
Update transform info to camera node 
.PP
Reimplemented from \fBme::Component\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool me::Camera::mAutoRadio\fC [protected]\fP"

.SS "int me::Camera::mFarDistance\fC [protected]\fP"

.SS "\fBVector3\fP me::Camera::mLookAt\fC [protected]\fP"

.SS "std::string me::Camera::mName\fC [protected]\fP"

.SS "int me::Camera::mNearDistance\fC [protected]\fP"

.SS "bool me::Camera::mStaticObject = true\fC [protected]\fP"

.SS "\fBTransform\fP* me::Camera::mTransform\fC [protected]\fP"

.SS "int me::Camera::mZOrder\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
