.TH "me::DebugDrawer" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::DebugDrawer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DebugDrawer\&.h>\fP
.PP
Inherits btIDebugDraw\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDebugDrawer\fP ()"
.br
.ti -1c
.RI "\fB~DebugDrawer\fP ()"
.br
.ti -1c
.RI "virtual void \fBdrawTriangle\fP (const btVector3 &v0, const btVector3 &v1, const btVector3 &v2, const btVector3 &color, btScalar alpha) override"
.br
.ti -1c
.RI "void \fBdrawLine\fP (const btVector3 &from, const btVector3 &to, const btVector3 &color) override"
.br
.ti -1c
.RI "void \fBdrawContactPoint\fP (const btVector3 &PointOnB, const btVector3 &normalOnB, btScalar distance, int lifeTime, const btVector3 &color) override"
.br
.ti -1c
.RI "void \fBreportErrorWarning\fP (const char *warningString) override"
.br
.ti -1c
.RI "void \fBdraw3dText\fP (const btVector3 &location, const char *textString) override"
.br
.ti -1c
.RI "void \fBsetDebugMode\fP (int debugMode) override"
.br
.ti -1c
.RI "int \fBgetDebugMode\fP () const override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "me::DebugDrawer::DebugDrawer ()"

.SS "me::DebugDrawer::~DebugDrawer ()"

.SH "Member Function Documentation"
.PP 
.SS "void me::DebugDrawer::draw3dText (const btVector3 & location, const char * textString)\fC [override]\fP"

.SS "void me::DebugDrawer::drawContactPoint (const btVector3 & PointOnB, const btVector3 & normalOnB, btScalar distance, int lifeTime, const btVector3 & color)\fC [override]\fP"

.SS "void me::DebugDrawer::drawLine (const btVector3 & from, const btVector3 & to, const btVector3 & color)\fC [override]\fP"

.SS "void me::DebugDrawer::drawTriangle (const btVector3 & v0, const btVector3 & v1, const btVector3 & v2, const btVector3 & color, btScalar alpha)\fC [override]\fP, \fC [virtual]\fP"

.SS "int me::DebugDrawer::getDebugMode () const\fC [override]\fP"

.SS "void me::DebugDrawer::reportErrorWarning (const char * warningString)\fC [override]\fP"

.SS "void me::DebugDrawer::setDebugMode (int debugMode)\fC [override]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
