.TH "me::Input" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::Input
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Button\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBInput\fP &i) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InputType \fBtype\fP"
.br
.ti -1c
.RI "int \fBwhich\fP"
.br
.ti -1c
.RI "float \fBvalue\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool me::Input::operator== (const \fBInput\fP & i) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "InputType me::Input::type"

.SS "float me::Input::value"

.SS "int me::Input::which"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
