.TH "me::InputHasher" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::InputHasher
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Button\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const \fBInput\fP &t) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "size_t me::InputHasher::operator() (const \fBInput\fP & t) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
