.TH "me::MotorEngine" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::MotorEngine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MotorEngine\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMotorEngine\fP ()"
.br
.ti -1c
.RI "\fB~MotorEngine\fP ()"
.br
.ti -1c
.RI "bool \fBsetup\fP (std::string gameName='VroomVroom')"
.br
.ti -1c
.RI "void \fBloop\fP ()"
.br
.ti -1c
.RI "void \fBexit\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MotorEngine::MotorEngine ()"

.SS "MotorEngine::~MotorEngine ()"

.SH "Member Function Documentation"
.PP 
.SS "void MotorEngine::exit ()"

.SS "void MotorEngine::loop ()"

.SS "bool MotorEngine::setup (std::string gameName = \fC'VroomVroom'\fP)"
Loads and initializates the engine and the game\&. Automatically loads a _d sufix dll if _DEBUG flags is defined\&. @params gameName Name of the \&.dll of the game, without any sufixes 

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
