.TH "me::OnButtonPressedInfo" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::OnButtonPressedInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Button\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBcallback\fP )(void *)"
.br
.ti -1c
.RI "void * \fBadditionalData\fP"
.br
.ti -1c
.RI "\fBSDL_EventFilter\fP \fBfilter\fP"
.br
.ti -1c
.RI "std::unordered_multimap< \fBInput\fP, std::string, \fBInputHasher\fP > * \fBbuttonBindings\fP"
.br
.ti -1c
.RI "std::string \fBbuttonName\fP"
.br
.ti -1c
.RI "int \fBplayer\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* me::OnButtonPressedInfo::additionalData"

.SS "std::unordered_multimap<\fBInput\fP, std::string, \fBInputHasher\fP>* me::OnButtonPressedInfo::buttonBindings"

.SS "std::string me::OnButtonPressedInfo::buttonName"

.SS "int(* me::OnButtonPressedInfo::callback) (void *)"

.SS "\fBSDL_EventFilter\fP me::OnButtonPressedInfo::filter"

.SS "int me::OnButtonPressedInfo::player"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
