.TH "me::RenderWindow" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::RenderWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RenderWindow\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderWindow\fP (const std::string windowName)"
.br
.ti -1c
.RI "\fB~RenderWindow\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP (Ogre::Root *root)"
.br
.ti -1c
.RI "Ogre::RenderWindow * \fBgetRenderWindow\fP ()"
.br
.ti -1c
.RI "\fBSDL_Window\fP * \fBgetSdlWindow\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateWindow\fP (Ogre::Root *root)"
.br
.ti -1c
.RI "void \fBsetWindowGrab\fP (bool _grab)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmWindowName\fP"
.br
.ti -1c
.RI "\fBSDL_Window\fP * \fBmSdlWindow\fP = nullptr"
.br
.ti -1c
.RI "Ogre::RenderWindow * \fBmRenderWindow\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class to create linked window between SDL_window and Ogre::RendererWindow 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RenderWindow::RenderWindow (const std::string windowName)"

.SS "RenderWindow::~RenderWindow ()"

.SH "Member Function Documentation"
.PP 
.SS "void RenderWindow::createWindow (Ogre::Root * root)\fC [protected]\fP"
Get configuration information, Sdl window, Sdl window information and create Ogre::Render window with all the information mentioned It is linked window between SDL window and Ogre::Render window 
.PP
\fBParameters\fP
.RS 4
\fIroot:reference\fP of Ogre::Root created by OgreManager 
.RE
.PP

.SS "Ogre::RenderWindow * me::RenderWindow::getRenderWindow ()"

.SS "\fBSDL_Window\fP * me::RenderWindow::getSdlWindow ()"

.SS "void RenderWindow::init (Ogre::Root * root)"
Initialize linked window without automatically window created 
.PP
\fBParameters\fP
.RS 4
\fIroot:reference\fP of Ogre::Root created by OgreManager 
.RE
.PP

.SS "void RenderWindow::setWindowGrab (bool _grab)\fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "Ogre::RenderWindow* me::RenderWindow::mRenderWindow = nullptr\fC [protected]\fP"

.SS "\fBSDL_Window\fP* me::RenderWindow::mSdlWindow = nullptr\fC [protected]\fP"

.SS "std::string me::RenderWindow::mWindowName\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
