.TH "me::SGTechniqueResolverListener" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
me::SGTechniqueResolverListener
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SGTechniqueResolverListener\&.h>\fP
.PP
Inherits Ogre::MaterialManager::Listener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSGTechniqueResolverListener\fP (Ogre::RTShader::ShaderGenerator *pShaderGenerator)"
.br
.ti -1c
.RI "Ogre::Technique * \fBhandleSchemeNotFound\fP (unsigned short schemeIndex, const Ogre::String &schemeName, Ogre::Material *originalMaterial, unsigned short lodIndex, const Ogre::Renderable *rend) override"
.br
.ti -1c
.RI "bool \fBafterIlluminationPassesCreated\fP (Ogre::Technique *tech) override"
.br
.ti -1c
.RI "bool \fBbeforeIlluminationPassesCleared\fP (Ogre::Technique *tech) override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Ogre::RTShader::ShaderGenerator * \fBmShaderGenerator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Default implementation of a Listener to use with the \fBOgre::RTShader\fP system\&. When a target scheme callback is invoked with the shader generator scheme it tries to create an equivalent shader based technique based on the default technique of the given material\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "me::SGTechniqueResolverListener::SGTechniqueResolverListener (Ogre::RTShader::ShaderGenerator * pShaderGenerator)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool me::SGTechniqueResolverListener::afterIlluminationPassesCreated (Ogre::Technique * tech)\fC [override]\fP"

.SS "bool me::SGTechniqueResolverListener::beforeIlluminationPassesCleared (Ogre::Technique * tech)\fC [override]\fP"

.SS "Ogre::Technique * me::SGTechniqueResolverListener::handleSchemeNotFound (unsigned short schemeIndex, const Ogre::String & schemeName, Ogre::Material * originalMaterial, unsigned short lodIndex, const Ogre::Renderable * rend)\fC [override]\fP"
This is the hook point where shader based technique will be created\&. It will be called whenever the material manager won't find appropriate technique that satisfy the target scheme name\&. If the scheme name is out target RT Shader System scheme name we will try to create shader generated technique for it\&. 
.SH "Member Data Documentation"
.PP 
.SS "Ogre::RTShader::ShaderGenerator* me::SGTechniqueResolverListener::mShaderGenerator\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
