.TH "Src/MotorEngine/MotorEngine.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/MotorEngine/MotorEngine.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MotorEngineAPI\&.h'\fP
.br
\fC#include <Windows\&.h>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBme::MotorEngine\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__MOTORENGINE_MOTORENGINE\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __MOTORENGINE_MOTORENGINE"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
