.TH "Src/MotorEngine/MotorEngineAPI.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/MotorEngine/MotorEngineAPI.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__MOTORENGINE_API\fP   __declspec(dllimport)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __MOTORENGINE_API   __declspec(dllimport)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
