.TH "Src/MotorEngine/MotorEngine.cpp" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/MotorEngine/MotorEngine.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MotorEngine\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <random>\fP
.br
\fC#include 'Audio/SoundManager\&.h'\fP
.br
\fC#include 'Physics/PhysicsManager\&.h'\fP
.br
\fC#include 'Render/RenderManager\&.h'\fP
.br
\fC#include 'Input/InputManager\&.h'\fP
.br
\fC#include 'EntityComponent/SceneManager\&.h'\fP
.br
\fC#include 'EntityComponent/Scene\&.h'\fP
.br
\fC#include 'Render/Window\&.h'\fP
.br
\fC#include 'EntityComponent/Components/ComponentsFactory\&.h'\fP
.br
\fC#include 'EntityComponent/Components/FactoryComponent\&.h'\fP
.br
\fC#include <SDL3/SDL_events\&.h>\fP
.br
\fC#include <SDL3/SDL_init\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef const char *(* \fBGameName\fP) ()"
.br
.ti -1c
.RI "typedef bool(__cdecl * \fBGameEntryPoint\fP) ()"
.br
.ti -1c
.RI "typedef void(* \fBTypeDefinition\fP) ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef bool(__cdecl * GameEntryPoint) ()"

.SS "typedef const char *(* GameName) ()"

.SS "typedef void(* TypeDefinition) ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
