.TH "nk_allocator" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_allocator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnk_handle\fP \fBuserdata\fP"
.br
.ti -1c
.RI "\fBnk_plugin_alloc\fP \fBalloc\fP"
.br
.ti -1c
.RI "\fBnk_plugin_free\fP \fBfree\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBnk_plugin_alloc\fP nk_allocator::alloc"

.SS "\fBnk_plugin_free\fP nk_allocator::free"

.SS "\fBnk_handle\fP nk_allocator::userdata"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
