.TH "nk_buffer_marker" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_buffer_marker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnk_bool\fP \fBactive\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBoffset\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBnk_bool\fP nk_buffer_marker::active"

.SS "\fBnk_size\fP nk_buffer_marker::offset"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
