.TH "nk_buffer" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_buffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_buffer_marker\fP \fBmarker\fP [\fBNK_BUFFER_MAX\fP]"
.br
.ti -1c
.RI "struct \fBnk_allocator\fP \fBpool\fP"
.br
.ti -1c
.RI "enum \fBnk_allocation_type\fP \fBtype\fP"
.br
.ti -1c
.RI "struct \fBnk_memory\fP \fBmemory\fP"
.br
.ti -1c
.RI "float \fBgrow_factor\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBallocated\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBneeded\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBcalls\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBsize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBnk_size\fP nk_buffer::allocated"

.SS "\fBnk_size\fP nk_buffer::calls"

.SS "float nk_buffer::grow_factor"

.SS "struct \fBnk_buffer_marker\fP nk_buffer::marker[\fBNK_BUFFER_MAX\fP]"

.SS "struct \fBnk_memory\fP nk_buffer::memory"

.SS "\fBnk_size\fP nk_buffer::needed"

.SS "struct \fBnk_allocator\fP nk_buffer::pool"

.SS "\fBnk_size\fP nk_buffer::size"

.SS "enum \fBnk_allocation_type\fP nk_buffer::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
