.TH "nk_chart_slot" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_chart_slot
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBnk_chart_type\fP \fBtype\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcolor\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBhighlight\fP"
.br
.ti -1c
.RI "float \fBmin\fP"
.br
.ti -1c
.RI "float \fBmax\fP"
.br
.ti -1c
.RI "float \fBrange\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBlast\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_color\fP nk_chart_slot::color"

.SS "int nk_chart_slot::count"

.SS "struct \fBnk_color\fP nk_chart_slot::highlight"

.SS "int nk_chart_slot::index"

.SS "struct \fBnk_vec2\fP nk_chart_slot::last"

.SS "float nk_chart_slot::max"

.SS "float nk_chart_slot::min"

.SS "float nk_chart_slot::range"

.SS "enum \fBnk_chart_type\fP nk_chart_slot::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
