.TH "nk_chart" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_chart
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBslot\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "struct \fBnk_chart_slot\fP \fBslots\fP [\fBNK_CHART_MAX_SLOT\fP]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float nk_chart::h"

.SS "int nk_chart::slot"

.SS "struct \fBnk_chart_slot\fP nk_chart::slots[\fBNK_CHART_MAX_SLOT\fP]"

.SS "float nk_chart::w"

.SS "float nk_chart::x"

.SS "float nk_chart::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
