.TH "nk_convert_config" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_convert_config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBglobal_alpha\fP"
.br
.ti -1c
.RI "enum \fBnk_anti_aliasing\fP \fBline_AA\fP"
.br
.ti -1c
.RI "enum \fBnk_anti_aliasing\fP \fBshape_AA\fP"
.br
.ti -1c
.RI "unsigned \fBcircle_segment_count\fP"
.br
.ti -1c
.RI "unsigned \fBarc_segment_count\fP"
.br
.ti -1c
.RI "unsigned \fBcurve_segment_count\fP"
.br
.ti -1c
.RI "struct \fBnk_draw_null_texture\fP \fBtex_null\fP"
.br
.ti -1c
.RI "const struct nk_draw_vertex_layout_element * \fBvertex_layout\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBvertex_size\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBvertex_alignment\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned nk_convert_config::arc_segment_count"

.SS "unsigned nk_convert_config::circle_segment_count"

.SS "unsigned nk_convert_config::curve_segment_count"

.SS "float nk_convert_config::global_alpha"

.SS "enum \fBnk_anti_aliasing\fP nk_convert_config::line_AA"

.SS "enum \fBnk_anti_aliasing\fP nk_convert_config::shape_AA"

.SS "struct \fBnk_draw_null_texture\fP nk_convert_config::tex_null"

.SS "\fBnk_size\fP nk_convert_config::vertex_alignment"

.SS "const struct nk_draw_vertex_layout_element* nk_convert_config::vertex_layout"

.SS "\fBnk_size\fP nk_convert_config::vertex_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
