.TH "nk_context" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_context
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_input\fP \fBinput\fP"
.br
.ti -1c
.RI "struct \fBnk_style\fP \fBstyle\fP"
.br
.ti -1c
.RI "struct \fBnk_buffer\fP \fBmemory\fP"
.br
.ti -1c
.RI "struct \fBnk_clipboard\fP \fBclip\fP"
.br
.ti -1c
.RI "\fBnk_flags\fP \fBlast_widget_state\fP"
.br
.ti -1c
.RI "enum \fBnk_button_behavior\fP \fBbutton_behavior\fP"
.br
.ti -1c
.RI "struct \fBnk_configuration_stacks\fP \fBstacks\fP"
.br
.ti -1c
.RI "float \fBdelta_time_seconds\fP"
.br
.ti -1c
.RI "struct \fBnk_text_edit\fP \fBtext_edit\fP"
.br
.ti -1c
.RI "struct \fBnk_command_buffer\fP \fBoverlay\fP"
.br
.ti -1c
.RI "int \fBbuild\fP"
.br
.ti -1c
.RI "int \fBuse_pool\fP"
.br
.ti -1c
.RI "struct \fBnk_pool\fP \fBpool\fP"
.br
.ti -1c
.RI "struct \fBnk_window\fP * \fBbegin\fP"
.br
.ti -1c
.RI "struct \fBnk_window\fP * \fBend\fP"
.br
.ti -1c
.RI "struct \fBnk_window\fP * \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_window\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "struct \fBnk_page_element\fP * \fBfreelist\fP"
.br
.ti -1c
.RI "unsigned int \fBcount\fP"
.br
.ti -1c
.RI "unsigned int \fBseq\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_window\fP* nk_context::active"

.SS "struct \fBnk_window\fP* nk_context::begin"

.SS "int nk_context::build"

.SS "enum \fBnk_button_behavior\fP nk_context::button_behavior"

.SS "struct \fBnk_clipboard\fP nk_context::clip"

.SS "unsigned int nk_context::count"

.SS "struct \fBnk_window\fP* nk_context::current"

.SS "float nk_context::delta_time_seconds"

.SS "struct \fBnk_window\fP* nk_context::end"

.SS "struct \fBnk_page_element\fP* nk_context::freelist"

.SS "struct \fBnk_input\fP nk_context::input"

.SS "\fBnk_flags\fP nk_context::last_widget_state"

.SS "struct \fBnk_buffer\fP nk_context::memory"

.SS "struct \fBnk_command_buffer\fP nk_context::overlay"

.SS "struct \fBnk_pool\fP nk_context::pool"

.SS "unsigned int nk_context::seq"

.SS "struct \fBnk_configuration_stacks\fP nk_context::stacks"

.SS "struct \fBnk_style\fP nk_context::style"

.SS "struct \fBnk_text_edit\fP nk_context::text_edit"

.SS "int nk_context::use_pool"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
