.TH "nk_configuration_stacks" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_configuration_stacks
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct nk_config_stack_style_item \fBstyle_items\fP"
.br
.ti -1c
.RI "struct nk_config_stack_float \fBfloats\fP"
.br
.ti -1c
.RI "struct nk_config_stack_vec2 \fBvectors\fP"
.br
.ti -1c
.RI "struct nk_config_stack_flags \fBflags\fP"
.br
.ti -1c
.RI "struct nk_config_stack_color \fBcolors\fP"
.br
.ti -1c
.RI "struct nk_config_stack_user_font \fBfonts\fP"
.br
.ti -1c
.RI "struct nk_config_stack_button_behavior \fBbutton_behaviors\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct nk_config_stack_button_behavior nk_configuration_stacks::button_behaviors"

.SS "struct nk_config_stack_color nk_configuration_stacks::colors"

.SS "struct nk_config_stack_flags nk_configuration_stacks::flags"

.SS "struct nk_config_stack_float nk_configuration_stacks::floats"

.SS "struct nk_config_stack_user_font nk_configuration_stacks::fonts"

.SS "struct nk_config_stack_style_item nk_configuration_stacks::style_items"

.SS "struct nk_config_stack_vec2 nk_configuration_stacks::vectors"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
