.TH "nk_command_buffer" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_command_buffer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_buffer\fP * \fBbase\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBclip\fP"
.br
.ti -1c
.RI "int \fBuse_clipping\fP"
.br
.ti -1c
.RI "\fBnk_handle\fP \fBuserdata\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBbegin\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBend\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBlast\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_buffer\fP* nk_command_buffer::base"

.SS "\fBnk_size\fP nk_command_buffer::begin"

.SS "struct \fBnk_rect\fP nk_command_buffer::clip"

.SS "\fBnk_size\fP nk_command_buffer::end"

.SS "\fBnk_size\fP nk_command_buffer::last"

.SS "int nk_command_buffer::use_clipping"

.SS "\fBnk_handle\fP nk_command_buffer::userdata"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
