.TH "nk_command_text" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_command_text
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_command\fP \fBheader\fP"
.br
.ti -1c
.RI "const struct \fBnk_user_font\fP * \fBfont\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBbackground\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBforeground\fP"
.br
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.ti -1c
.RI "unsigned short \fBw\fP"
.br
.ti -1c
.RI "unsigned short \fBh\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "char \fBstring\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_color\fP nk_command_text::background"

.SS "const struct \fBnk_user_font\fP* nk_command_text::font"

.SS "struct \fBnk_color\fP nk_command_text::foreground"

.SS "unsigned short nk_command_text::h"

.SS "struct \fBnk_command\fP nk_command_text::header"

.SS "float nk_command_text::height"

.SS "int nk_command_text::length"

.SS "char nk_command_text::string[1]"

.SS "unsigned short nk_command_text::w"

.SS "short nk_command_text::x"

.SS "short nk_command_text::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
