.TH "nk_cursor" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_cursor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_image\fP \fBimg\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP size \fBoffset\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_image\fP nk_cursor::img"

.SS "struct \fBnk_vec2\fP size nk_cursor::offset"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
