.TH "nk_command_polyline" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_command_polyline
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_command\fP \fBheader\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcolor\fP"
.br
.ti -1c
.RI "unsigned short \fBline_thickness\fP"
.br
.ti -1c
.RI "unsigned short \fBpoint_count\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2i\fP \fBpoints\fP [1]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_color\fP nk_command_polyline::color"

.SS "struct \fBnk_command\fP nk_command_polyline::header"

.SS "unsigned short nk_command_polyline::line_thickness"

.SS "unsigned short nk_command_polyline::point_count"

.SS "struct \fBnk_vec2i\fP nk_command_polyline::points[1]"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
