.TH "nk_draw_null_texture" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_draw_null_texture
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnk_handle\fP \fBtexture\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBuv\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBnk_handle\fP nk_draw_null_texture::texture"

.SS "struct \fBnk_vec2\fP nk_draw_null_texture::uv"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
