.TH "nk_edit_state" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_edit_state
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnk_hash\fP \fBname\fP"
.br
.ti -1c
.RI "unsigned int \fBseq\fP"
.br
.ti -1c
.RI "unsigned int \fBold\fP"
.br
.ti -1c
.RI "int \fBactive\fP"
.br
.ti -1c
.RI "int \fBprev\fP"
.br
.ti -1c
.RI "int \fBcursor\fP"
.br
.ti -1c
.RI "int \fBsel_start\fP"
.br
.ti -1c
.RI "int \fBsel_end\fP"
.br
.ti -1c
.RI "struct \fBnk_scroll\fP \fBscrollbar\fP"
.br
.ti -1c
.RI "unsigned char \fBmode\fP"
.br
.ti -1c
.RI "unsigned char \fBsingle_line\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int nk_edit_state::active"

.SS "int nk_edit_state::cursor"

.SS "unsigned char nk_edit_state::mode"

.SS "\fBnk_hash\fP nk_edit_state::name"

.SS "unsigned int nk_edit_state::old"

.SS "int nk_edit_state::prev"

.SS "struct \fBnk_scroll\fP nk_edit_state::scrollbar"

.SS "int nk_edit_state::sel_end"

.SS "int nk_edit_state::sel_start"

.SS "unsigned int nk_edit_state::seq"

.SS "unsigned char nk_edit_state::single_line"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
