.TH "nk_handle" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_handle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int nk_handle::id"

.SS "void* nk_handle::ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
