.TH "nk_keyboard" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_keyboard
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_key\fP \fBkeys\fP [\fBNK_KEY_MAX\fP]"
.br
.ti -1c
.RI "char \fBtext\fP [\fBNK_INPUT_MAX\fP]"
.br
.ti -1c
.RI "int \fBtext_len\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_key\fP nk_keyboard::keys[\fBNK_KEY_MAX\fP]"

.SS "char nk_keyboard::text[\fBNK_INPUT_MAX\fP]"

.SS "int nk_keyboard::text_len"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
