.TH "nk_key" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_key
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnk_bool\fP \fBdown\fP"
.br
.ti -1c
.RI "unsigned int \fBclicked\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned int nk_key::clicked"

.SS "\fBnk_bool\fP nk_key::down"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
