.TH "nk_list_view" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_list_view
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBbegin\fP"
.br
.ti -1c
.RI "int \fBend\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBtotal_height\fP"
.br
.ti -1c
.RI "struct \fBnk_context\fP * \fBctx\fP"
.br
.ti -1c
.RI "\fBnk_uint\fP * \fBscroll_pointer\fP"
.br
.ti -1c
.RI "\fBnk_uint\fP \fBscroll_value\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int nk_list_view::begin"

.SS "int nk_list_view::count"

.SS "struct \fBnk_context\fP* nk_list_view::ctx"

.SS "int nk_list_view::end"

.SS "\fBnk_uint\fP* nk_list_view::scroll_pointer"

.SS "\fBnk_uint\fP nk_list_view::scroll_value"

.SS "int nk_list_view::total_height"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
