.TH "nk_memory" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_memory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBsize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* nk_memory::ptr"

.SS "\fBnk_size\fP nk_memory::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
