.TH "nk_mouse" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_mouse
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_mouse_button\fP \fBbuttons\fP [\fBNK_BUTTON_MAX\fP]"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpos\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBprev\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBdelta\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBscroll_delta\fP"
.br
.ti -1c
.RI "unsigned char \fBgrab\fP"
.br
.ti -1c
.RI "unsigned char \fBgrabbed\fP"
.br
.ti -1c
.RI "unsigned char \fBungrab\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_mouse_button\fP nk_mouse::buttons[\fBNK_BUTTON_MAX\fP]"

.SS "struct \fBnk_vec2\fP nk_mouse::delta"

.SS "unsigned char nk_mouse::grab"

.SS "unsigned char nk_mouse::grabbed"

.SS "struct \fBnk_vec2\fP nk_mouse::pos"

.SS "struct \fBnk_vec2\fP nk_mouse::prev"

.SS "struct \fBnk_vec2\fP nk_mouse::scroll_delta"

.SS "unsigned char nk_mouse::ungrab"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
