.TH "nk_memory_status" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_memory_status
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBmemory\fP"
.br
.ti -1c
.RI "unsigned int \fBtype\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBallocated\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBneeded\fP"
.br
.ti -1c
.RI "\fBnk_size\fP \fBcalls\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBnk_size\fP nk_memory_status::allocated"

.SS "\fBnk_size\fP nk_memory_status::calls"

.SS "void* nk_memory_status::memory"

.SS "\fBnk_size\fP nk_memory_status::needed"

.SS "\fBnk_size\fP nk_memory_status::size"

.SS "unsigned int nk_memory_status::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
