.TH "nk_popup_state" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_popup_state
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_window\fP * \fBwin\fP"
.br
.ti -1c
.RI "enum \fBnk_panel_type\fP \fBtype\fP"
.br
.ti -1c
.RI "struct \fBnk_popup_buffer\fP \fBbuf\fP"
.br
.ti -1c
.RI "\fBnk_hash\fP \fBname\fP"
.br
.ti -1c
.RI "\fBnk_bool\fP \fBactive\fP"
.br
.ti -1c
.RI "unsigned \fBcombo_count\fP"
.br
.ti -1c
.RI "unsigned \fBcon_count\fP"
.br
.ti -1c
.RI "unsigned \fBcon_old\fP"
.br
.ti -1c
.RI "unsigned \fBactive_con\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBheader\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBnk_bool\fP nk_popup_state::active"

.SS "unsigned nk_popup_state::active_con"

.SS "struct \fBnk_popup_buffer\fP nk_popup_state::buf"

.SS "unsigned nk_popup_state::combo_count"

.SS "unsigned nk_popup_state::con_count"

.SS "unsigned nk_popup_state::con_old"

.SS "struct \fBnk_rect\fP nk_popup_state::header"

.SS "\fBnk_hash\fP nk_popup_state::name"

.SS "enum \fBnk_panel_type\fP nk_popup_state::type"

.SS "struct \fBnk_window\fP* nk_popup_state::win"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
