.TH "nk_page_element" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_page_element
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union \fBnk_page_data\fP \fBdata\fP"
.br
.ti -1c
.RI "struct \fBnk_page_element\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBnk_page_element\fP * \fBprev\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "union \fBnk_page_data\fP nk_page_element::data"

.SS "struct \fBnk_page_element\fP* nk_page_element::next"

.SS "struct \fBnk_page_element\fP* nk_page_element::prev"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
