.TH "nk_page_data" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_page_data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_table\fP \fBtbl\fP"
.br
.ti -1c
.RI "struct \fBnk_panel\fP \fBpan\fP"
.br
.ti -1c
.RI "struct \fBnk_window\fP \fBwin\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_panel\fP nk_page_data::pan"

.SS "struct \fBnk_table\fP nk_page_data::tbl"

.SS "struct \fBnk_window\fP nk_page_data::win"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
