.TH "nk_panel" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_panel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBnk_panel_type\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBnk_flags\fP \fBflags\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBbounds\fP"
.br
.ti -1c
.RI "\fBnk_uint\fP * \fBoffset_x\fP"
.br
.ti -1c
.RI "\fBnk_uint\fP * \fBoffset_y\fP"
.br
.ti -1c
.RI "float \fBat_x\fP"
.br
.ti -1c
.RI "float \fBat_y\fP"
.br
.ti -1c
.RI "float \fBmax_x\fP"
.br
.ti -1c
.RI "float \fBfooter_height\fP"
.br
.ti -1c
.RI "float \fBheader_height\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "unsigned int \fBhas_scrolling\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBclip\fP"
.br
.ti -1c
.RI "struct \fBnk_menu_state\fP \fBmenu\fP"
.br
.ti -1c
.RI "struct \fBnk_row_layout\fP \fBrow\fP"
.br
.ti -1c
.RI "struct \fBnk_chart\fP \fBchart\fP"
.br
.ti -1c
.RI "struct \fBnk_command_buffer\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "struct \fBnk_panel\fP * \fBparent\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float nk_panel::at_x"

.SS "float nk_panel::at_y"

.SS "float nk_panel::border"

.SS "struct \fBnk_rect\fP nk_panel::bounds"

.SS "struct \fBnk_command_buffer\fP* nk_panel::buffer"

.SS "struct \fBnk_chart\fP nk_panel::chart"

.SS "struct \fBnk_rect\fP nk_panel::clip"

.SS "\fBnk_flags\fP nk_panel::flags"

.SS "float nk_panel::footer_height"

.SS "unsigned int nk_panel::has_scrolling"

.SS "float nk_panel::header_height"

.SS "float nk_panel::max_x"

.SS "struct \fBnk_menu_state\fP nk_panel::menu"

.SS "\fBnk_uint\fP* nk_panel::offset_x"

.SS "\fBnk_uint\fP* nk_panel::offset_y"

.SS "struct \fBnk_panel\fP* nk_panel::parent"

.SS "struct \fBnk_row_layout\fP nk_panel::row"

.SS "enum \fBnk_panel_type\fP nk_panel::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
