.TH "nk_property_state" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_property_state
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBactive\fP"
.br
.ti -1c
.RI "int \fBprev\fP"
.br
.ti -1c
.RI "char \fBbuffer\fP [\fBNK_MAX_NUMBER_BUFFER\fP]"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "int \fBcursor\fP"
.br
.ti -1c
.RI "int \fBselect_start\fP"
.br
.ti -1c
.RI "int \fBselect_end\fP"
.br
.ti -1c
.RI "\fBnk_hash\fP \fBname\fP"
.br
.ti -1c
.RI "unsigned int \fBseq\fP"
.br
.ti -1c
.RI "unsigned int \fBold\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int nk_property_state::active"

.SS "char nk_property_state::buffer[\fBNK_MAX_NUMBER_BUFFER\fP]"

.SS "int nk_property_state::cursor"

.SS "int nk_property_state::length"

.SS "\fBnk_hash\fP nk_property_state::name"

.SS "unsigned int nk_property_state::old"

.SS "int nk_property_state::prev"

.SS "int nk_property_state::select_end"

.SS "int nk_property_state::select_start"

.SS "unsigned int nk_property_state::seq"

.SS "int nk_property_state::state"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
