.TH "nk_recti" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_recti
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.ti -1c
.RI "short \fBw\fP"
.br
.ti -1c
.RI "short \fBh\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "short nk_recti::h"

.SS "short nk_recti::w"

.SS "short nk_recti::x"

.SS "short nk_recti::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
