.TH "nk_row_layout" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_row_layout
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBnk_panel_row_layout_type\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "float \fBmin_height\fP"
.br
.ti -1c
.RI "int \fBcolumns\fP"
.br
.ti -1c
.RI "const float * \fBratio\fP"
.br
.ti -1c
.RI "float \fBitem_width\fP"
.br
.ti -1c
.RI "float \fBitem_height\fP"
.br
.ti -1c
.RI "float \fBitem_offset\fP"
.br
.ti -1c
.RI "float \fBfilled\fP"
.br
.ti -1c
.RI "struct \fBnk_rect\fP \fBitem\fP"
.br
.ti -1c
.RI "int \fBtree_depth\fP"
.br
.ti -1c
.RI "float \fBtemplates\fP [\fBNK_MAX_LAYOUT_ROW_TEMPLATE_COLUMNS\fP]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int nk_row_layout::columns"

.SS "float nk_row_layout::filled"

.SS "float nk_row_layout::height"

.SS "int nk_row_layout::index"

.SS "struct \fBnk_rect\fP nk_row_layout::item"

.SS "float nk_row_layout::item_height"

.SS "float nk_row_layout::item_offset"

.SS "float nk_row_layout::item_width"

.SS "float nk_row_layout::min_height"

.SS "const float* nk_row_layout::ratio"

.SS "float nk_row_layout::templates[\fBNK_MAX_LAYOUT_ROW_TEMPLATE_COLUMNS\fP]"

.SS "int nk_row_layout::tree_depth"

.SS "enum \fBnk_panel_row_layout_type\fP nk_row_layout::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
