.TH "nk_style_button" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_button
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_background\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_active\fP"
.br
.ti -1c
.RI "\fBnk_flags\fP \fBtext_alignment\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBimage_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBtouch_padding\fP"
.br
.ti -1c
.RI "\fBnk_handle\fP \fBuserdata\fP"
.br
.ti -1c
.RI "void(* \fBdraw_begin\fP )(struct \fBnk_command_buffer\fP *, \fBnk_handle\fP \fBuserdata\fP)"
.br
.ti -1c
.RI "void(* \fBdraw_end\fP )(struct \fBnk_command_buffer\fP *, \fBnk_handle\fP \fBuserdata\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_style_item\fP nk_style_button::active"

.SS "float nk_style_button::border"

.SS "struct \fBnk_color\fP nk_style_button::border_color"

.SS "void(* nk_style_button::draw_begin) (struct \fBnk_command_buffer\fP *, \fBnk_handle\fP \fBuserdata\fP)"

.SS "void(* nk_style_button::draw_end) (struct \fBnk_command_buffer\fP *, \fBnk_handle\fP \fBuserdata\fP)"

.SS "struct \fBnk_style_item\fP nk_style_button::hover"

.SS "struct \fBnk_vec2\fP nk_style_button::image_padding"

.SS "struct \fBnk_style_item\fP nk_style_button::normal"

.SS "struct \fBnk_vec2\fP nk_style_button::padding"

.SS "float nk_style_button::rounding"

.SS "struct \fBnk_color\fP nk_style_button::text_active"

.SS "\fBnk_flags\fP nk_style_button::text_alignment"

.SS "struct \fBnk_color\fP nk_style_button::text_background"

.SS "struct \fBnk_color\fP nk_style_button::text_hover"

.SS "struct \fBnk_color\fP nk_style_button::text_normal"

.SS "struct \fBnk_vec2\fP nk_style_button::touch_padding"

.SS "\fBnk_handle\fP nk_style_button::userdata"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
