.TH "nk_style_edit" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_edit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_style_scrollbar\fP \fBscrollbar\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcursor_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcursor_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcursor_text_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcursor_text_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_active\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBselected_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBselected_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBselected_text_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBselected_text_hover\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "float \fBcursor_size\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBscrollbar_size\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "float \fBrow_padding\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_style_item\fP nk_style_edit::active"

.SS "float nk_style_edit::border"

.SS "struct \fBnk_color\fP nk_style_edit::border_color"

.SS "struct \fBnk_color\fP nk_style_edit::cursor_hover"

.SS "struct \fBnk_color\fP nk_style_edit::cursor_normal"

.SS "float nk_style_edit::cursor_size"

.SS "struct \fBnk_color\fP nk_style_edit::cursor_text_hover"

.SS "struct \fBnk_color\fP nk_style_edit::cursor_text_normal"

.SS "struct \fBnk_style_item\fP nk_style_edit::hover"

.SS "struct \fBnk_style_item\fP nk_style_edit::normal"

.SS "struct \fBnk_vec2\fP nk_style_edit::padding"

.SS "float nk_style_edit::rounding"

.SS "float nk_style_edit::row_padding"

.SS "struct \fBnk_style_scrollbar\fP nk_style_edit::scrollbar"

.SS "struct \fBnk_vec2\fP nk_style_edit::scrollbar_size"

.SS "struct \fBnk_color\fP nk_style_edit::selected_hover"

.SS "struct \fBnk_color\fP nk_style_edit::selected_normal"

.SS "struct \fBnk_color\fP nk_style_edit::selected_text_hover"

.SS "struct \fBnk_color\fP nk_style_edit::selected_text_normal"

.SS "struct \fBnk_color\fP nk_style_edit::text_active"

.SS "struct \fBnk_color\fP nk_style_edit::text_hover"

.SS "struct \fBnk_color\fP nk_style_edit::text_normal"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
