.TH "nk_style_chart" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_chart
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBbackground\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBselected_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcolor\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_style_item\fP nk_style_chart::background"

.SS "float nk_style_chart::border"

.SS "struct \fBnk_color\fP nk_style_chart::border_color"

.SS "struct \fBnk_color\fP nk_style_chart::color"

.SS "struct \fBnk_vec2\fP nk_style_chart::padding"

.SS "float nk_style_chart::rounding"

.SS "struct \fBnk_color\fP nk_style_chart::selected_color"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
