.TH "nk_style" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const struct \fBnk_user_font\fP * \fBfont\fP"
.br
.ti -1c
.RI "const struct \fBnk_cursor\fP * \fBcursors\fP [\fBNK_CURSOR_COUNT\fP]"
.br
.ti -1c
.RI "const struct \fBnk_cursor\fP * \fBcursor_active\fP"
.br
.ti -1c
.RI "struct \fBnk_cursor\fP * \fBcursor_last\fP"
.br
.ti -1c
.RI "int \fBcursor_visible\fP"
.br
.ti -1c
.RI "struct \fBnk_style_text\fP \fBtext\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBbutton\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBcontextual_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBmenu_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_toggle\fP \fBoption\fP"
.br
.ti -1c
.RI "struct \fBnk_style_toggle\fP \fBcheckbox\fP"
.br
.ti -1c
.RI "struct \fBnk_style_selectable\fP \fBselectable\fP"
.br
.ti -1c
.RI "struct \fBnk_style_slider\fP \fBslider\fP"
.br
.ti -1c
.RI "struct \fBnk_style_progress\fP \fBprogress\fP"
.br
.ti -1c
.RI "struct \fBnk_style_property\fP \fBproperty\fP"
.br
.ti -1c
.RI "struct \fBnk_style_edit\fP \fBedit\fP"
.br
.ti -1c
.RI "struct \fBnk_style_chart\fP \fBchart\fP"
.br
.ti -1c
.RI "struct \fBnk_style_scrollbar\fP \fBscrollh\fP"
.br
.ti -1c
.RI "struct \fBnk_style_scrollbar\fP \fBscrollv\fP"
.br
.ti -1c
.RI "struct \fBnk_style_tab\fP \fBtab\fP"
.br
.ti -1c
.RI "struct \fBnk_style_combo\fP \fBcombo\fP"
.br
.ti -1c
.RI "struct \fBnk_style_window\fP \fBwindow\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_style_button\fP nk_style::button"

.SS "struct \fBnk_style_chart\fP nk_style::chart"

.SS "struct \fBnk_style_toggle\fP nk_style::checkbox"

.SS "struct \fBnk_style_combo\fP nk_style::combo"

.SS "struct \fBnk_style_button\fP nk_style::contextual_button"

.SS "const struct \fBnk_cursor\fP* nk_style::cursor_active"

.SS "struct \fBnk_cursor\fP* nk_style::cursor_last"

.SS "int nk_style::cursor_visible"

.SS "const struct \fBnk_cursor\fP* nk_style::cursors[\fBNK_CURSOR_COUNT\fP]"

.SS "struct \fBnk_style_edit\fP nk_style::edit"

.SS "const struct \fBnk_user_font\fP* nk_style::font"

.SS "struct \fBnk_style_button\fP nk_style::menu_button"

.SS "struct \fBnk_style_toggle\fP nk_style::option"

.SS "struct \fBnk_style_progress\fP nk_style::progress"

.SS "struct \fBnk_style_property\fP nk_style::property"

.SS "struct \fBnk_style_scrollbar\fP nk_style::scrollh"

.SS "struct \fBnk_style_scrollbar\fP nk_style::scrollv"

.SS "struct \fBnk_style_selectable\fP nk_style::selectable"

.SS "struct \fBnk_style_slider\fP nk_style::slider"

.SS "struct \fBnk_style_tab\fP nk_style::tab"

.SS "struct \fBnk_style_text\fP nk_style::text"

.SS "struct \fBnk_style_window\fP nk_style::window"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
