.TH "nk_style_selectable" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_selectable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBpressed\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal_active\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover_active\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBpressed_active\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_pressed\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_normal_active\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_hover_active\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_pressed_active\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext_background\fP"
.br
.ti -1c
.RI "\fBnk_flags\fP \fBtext_alignment\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBtouch_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBimage_padding\fP"
.br
.ti -1c
.RI "\fBnk_handle\fP \fBuserdata\fP"
.br
.ti -1c
.RI "void(* \fBdraw_begin\fP )(struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"
.br
.ti -1c
.RI "void(* \fBdraw_end\fP )(struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void(* nk_style_selectable::draw_begin) (struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"

.SS "void(* nk_style_selectable::draw_end) (struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"

.SS "struct \fBnk_style_item\fP nk_style_selectable::hover"

.SS "struct \fBnk_style_item\fP nk_style_selectable::hover_active"

.SS "struct \fBnk_vec2\fP nk_style_selectable::image_padding"

.SS "struct \fBnk_style_item\fP nk_style_selectable::normal"

.SS "struct \fBnk_style_item\fP nk_style_selectable::normal_active"

.SS "struct \fBnk_vec2\fP nk_style_selectable::padding"

.SS "struct \fBnk_style_item\fP nk_style_selectable::pressed"

.SS "struct \fBnk_style_item\fP nk_style_selectable::pressed_active"

.SS "float nk_style_selectable::rounding"

.SS "\fBnk_flags\fP nk_style_selectable::text_alignment"

.SS "struct \fBnk_color\fP nk_style_selectable::text_background"

.SS "struct \fBnk_color\fP nk_style_selectable::text_hover"

.SS "struct \fBnk_color\fP nk_style_selectable::text_hover_active"

.SS "struct \fBnk_color\fP nk_style_selectable::text_normal"

.SS "struct \fBnk_color\fP nk_style_selectable::text_normal_active"

.SS "struct \fBnk_color\fP nk_style_selectable::text_pressed"

.SS "struct \fBnk_color\fP nk_style_selectable::text_pressed_active"

.SS "struct \fBnk_vec2\fP nk_style_selectable::touch_padding"

.SS "\fBnk_handle\fP nk_style_selectable::userdata"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
