.TH "nk_scroll" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_scroll
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnk_uint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBnk_uint\fP \fBy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBnk_uint\fP nk_scroll::x"

.SS "\fBnk_uint\fP nk_scroll::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
