.TH "nk_style_combo" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_combo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_active\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBsymbol_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBsymbol_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBsymbol_active\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBbutton\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBsym_normal\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBsym_hover\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBsym_active\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBcontent_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBbutton_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBspacing\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_style_item\fP nk_style_combo::active"

.SS "float nk_style_combo::border"

.SS "struct \fBnk_color\fP nk_style_combo::border_color"

.SS "struct \fBnk_style_button\fP nk_style_combo::button"

.SS "struct \fBnk_vec2\fP nk_style_combo::button_padding"

.SS "struct \fBnk_vec2\fP nk_style_combo::content_padding"

.SS "struct \fBnk_style_item\fP nk_style_combo::hover"

.SS "struct \fBnk_color\fP nk_style_combo::label_active"

.SS "struct \fBnk_color\fP nk_style_combo::label_hover"

.SS "struct \fBnk_color\fP nk_style_combo::label_normal"

.SS "struct \fBnk_style_item\fP nk_style_combo::normal"

.SS "float nk_style_combo::rounding"

.SS "struct \fBnk_vec2\fP nk_style_combo::spacing"

.SS "enum \fBnk_symbol_type\fP nk_style_combo::sym_active"

.SS "enum \fBnk_symbol_type\fP nk_style_combo::sym_hover"

.SS "enum \fBnk_symbol_type\fP nk_style_combo::sym_normal"

.SS "struct \fBnk_color\fP nk_style_combo::symbol_active"

.SS "struct \fBnk_color\fP nk_style_combo::symbol_hover"

.SS "struct \fBnk_color\fP nk_style_combo::symbol_normal"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
