.TH "nk_style_window_header" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_window_header
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBclose_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBminimize_button\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBclose_symbol\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBminimize_symbol\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBmaximize_symbol\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_active\fP"
.br
.ti -1c
.RI "enum \fBnk_style_header_align\fP \fBalign\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBlabel_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBspacing\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_style_item\fP nk_style_window_header::active"

.SS "enum \fBnk_style_header_align\fP nk_style_window_header::align"

.SS "struct \fBnk_style_button\fP nk_style_window_header::close_button"

.SS "enum \fBnk_symbol_type\fP nk_style_window_header::close_symbol"

.SS "struct \fBnk_style_item\fP nk_style_window_header::hover"

.SS "struct \fBnk_color\fP nk_style_window_header::label_active"

.SS "struct \fBnk_color\fP nk_style_window_header::label_hover"

.SS "struct \fBnk_color\fP nk_style_window_header::label_normal"

.SS "struct \fBnk_vec2\fP nk_style_window_header::label_padding"

.SS "enum \fBnk_symbol_type\fP nk_style_window_header::maximize_symbol"

.SS "struct \fBnk_style_button\fP nk_style_window_header::minimize_button"

.SS "enum \fBnk_symbol_type\fP nk_style_window_header::minimize_symbol"

.SS "struct \fBnk_style_item\fP nk_style_window_header::normal"

.SS "struct \fBnk_vec2\fP nk_style_window_header::padding"

.SS "struct \fBnk_vec2\fP nk_style_window_header::spacing"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
