.TH "nk_style_item_data" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_item_data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_color\fP \fBcolor\fP"
.br
.ti -1c
.RI "struct \fBnk_image\fP \fBimage\fP"
.br
.ti -1c
.RI "struct \fBnk_nine_slice\fP \fBslice\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_color\fP nk_style_item_data::color"

.SS "struct \fBnk_image\fP nk_style_item_data::image"

.SS "struct \fBnk_nine_slice\fP nk_style_item_data::slice"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
