.TH "nk_style_property" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_property
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBnormal\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBhover\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBactive\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_normal\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_hover\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBlabel_active\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBsym_left\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBsym_right\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "struct \fBnk_style_edit\fP \fBedit\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBinc_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBdec_button\fP"
.br
.ti -1c
.RI "\fBnk_handle\fP \fBuserdata\fP"
.br
.ti -1c
.RI "void(* \fBdraw_begin\fP )(struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"
.br
.ti -1c
.RI "void(* \fBdraw_end\fP )(struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_style_item\fP nk_style_property::active"

.SS "float nk_style_property::border"

.SS "struct \fBnk_color\fP nk_style_property::border_color"

.SS "struct \fBnk_style_button\fP nk_style_property::dec_button"

.SS "void(* nk_style_property::draw_begin) (struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"

.SS "void(* nk_style_property::draw_end) (struct \fBnk_command_buffer\fP *, \fBnk_handle\fP)"

.SS "struct \fBnk_style_edit\fP nk_style_property::edit"

.SS "struct \fBnk_style_item\fP nk_style_property::hover"

.SS "struct \fBnk_style_button\fP nk_style_property::inc_button"

.SS "struct \fBnk_color\fP nk_style_property::label_active"

.SS "struct \fBnk_color\fP nk_style_property::label_hover"

.SS "struct \fBnk_color\fP nk_style_property::label_normal"

.SS "struct \fBnk_style_item\fP nk_style_property::normal"

.SS "struct \fBnk_vec2\fP nk_style_property::padding"

.SS "float nk_style_property::rounding"

.SS "enum \fBnk_symbol_type\fP nk_style_property::sym_left"

.SS "enum \fBnk_symbol_type\fP nk_style_property::sym_right"

.SS "\fBnk_handle\fP nk_style_property::userdata"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
