.TH "nk_style_window" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_window
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_window_header\fP \fBheader\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBfixed_background\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBbackground\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBpopup_border_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcombo_border_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBcontextual_border_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBmenu_border_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBgroup_border_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtooltip_border_color\fP"
.br
.ti -1c
.RI "struct \fBnk_style_item\fP \fBscaler\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBcombo_border\fP"
.br
.ti -1c
.RI "float \fBcontextual_border\fP"
.br
.ti -1c
.RI "float \fBmenu_border\fP"
.br
.ti -1c
.RI "float \fBgroup_border\fP"
.br
.ti -1c
.RI "float \fBtooltip_border\fP"
.br
.ti -1c
.RI "float \fBpopup_border\fP"
.br
.ti -1c
.RI "float \fBmin_row_height_padding\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBspacing\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBscrollbar_size\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBmin_size\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBgroup_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpopup_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBcombo_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBcontextual_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBmenu_padding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBtooltip_padding\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_color\fP nk_style_window::background"

.SS "float nk_style_window::border"

.SS "struct \fBnk_color\fP nk_style_window::border_color"

.SS "float nk_style_window::combo_border"

.SS "struct \fBnk_color\fP nk_style_window::combo_border_color"

.SS "struct \fBnk_vec2\fP nk_style_window::combo_padding"

.SS "float nk_style_window::contextual_border"

.SS "struct \fBnk_color\fP nk_style_window::contextual_border_color"

.SS "struct \fBnk_vec2\fP nk_style_window::contextual_padding"

.SS "struct \fBnk_style_item\fP nk_style_window::fixed_background"

.SS "float nk_style_window::group_border"

.SS "struct \fBnk_color\fP nk_style_window::group_border_color"

.SS "struct \fBnk_vec2\fP nk_style_window::group_padding"

.SS "struct \fBnk_style_window_header\fP nk_style_window::header"

.SS "float nk_style_window::menu_border"

.SS "struct \fBnk_color\fP nk_style_window::menu_border_color"

.SS "struct \fBnk_vec2\fP nk_style_window::menu_padding"

.SS "float nk_style_window::min_row_height_padding"

.SS "struct \fBnk_vec2\fP nk_style_window::min_size"

.SS "struct \fBnk_vec2\fP nk_style_window::padding"

.SS "float nk_style_window::popup_border"

.SS "struct \fBnk_color\fP nk_style_window::popup_border_color"

.SS "struct \fBnk_vec2\fP nk_style_window::popup_padding"

.SS "float nk_style_window::rounding"

.SS "struct \fBnk_style_item\fP nk_style_window::scaler"

.SS "struct \fBnk_vec2\fP nk_style_window::scrollbar_size"

.SS "struct \fBnk_vec2\fP nk_style_window::spacing"

.SS "float nk_style_window::tooltip_border"

.SS "struct \fBnk_color\fP nk_style_window::tooltip_border_color"

.SS "struct \fBnk_vec2\fP nk_style_window::tooltip_padding"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
