.TH "nk_style_tab" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_style_tab
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_style_item\fP \fBbackground\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBborder_color\fP"
.br
.ti -1c
.RI "struct \fBnk_color\fP \fBtext\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBtab_maximize_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBtab_minimize_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBnode_maximize_button\fP"
.br
.ti -1c
.RI "struct \fBnk_style_button\fP \fBnode_minimize_button\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBsym_minimize\fP"
.br
.ti -1c
.RI "enum \fBnk_symbol_type\fP \fBsym_maximize\fP"
.br
.ti -1c
.RI "float \fBborder\fP"
.br
.ti -1c
.RI "float \fBrounding\fP"
.br
.ti -1c
.RI "float \fBindent\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBpadding\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBspacing\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBnk_style_item\fP nk_style_tab::background"

.SS "float nk_style_tab::border"

.SS "struct \fBnk_color\fP nk_style_tab::border_color"

.SS "float nk_style_tab::indent"

.SS "struct \fBnk_style_button\fP nk_style_tab::node_maximize_button"

.SS "struct \fBnk_style_button\fP nk_style_tab::node_minimize_button"

.SS "struct \fBnk_vec2\fP nk_style_tab::padding"

.SS "float nk_style_tab::rounding"

.SS "struct \fBnk_vec2\fP nk_style_tab::spacing"

.SS "enum \fBnk_symbol_type\fP nk_style_tab::sym_maximize"

.SS "enum \fBnk_symbol_type\fP nk_style_tab::sym_minimize"

.SS "struct \fBnk_style_button\fP nk_style_tab::tab_maximize_button"

.SS "struct \fBnk_style_button\fP nk_style_tab::tab_minimize_button"

.SS "struct \fBnk_color\fP nk_style_tab::text"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
