.TH "nk_text_undo_record" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_text_undo_record
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwhere\fP"
.br
.ti -1c
.RI "short \fBinsert_length\fP"
.br
.ti -1c
.RI "short \fBdelete_length\fP"
.br
.ti -1c
.RI "short \fBchar_storage\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "short nk_text_undo_record::char_storage"

.SS "short nk_text_undo_record::delete_length"

.SS "short nk_text_undo_record::insert_length"

.SS "int nk_text_undo_record::where"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
