.TH "nk_text_edit" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_text_edit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBnk_clipboard\fP \fBclip\fP"
.br
.ti -1c
.RI "struct \fBnk_str\fP \fBstring\fP"
.br
.ti -1c
.RI "\fBnk_plugin_filter\fP \fBfilter\fP"
.br
.ti -1c
.RI "struct \fBnk_vec2\fP \fBscrollbar\fP"
.br
.ti -1c
.RI "int \fBcursor\fP"
.br
.ti -1c
.RI "int \fBselect_start\fP"
.br
.ti -1c
.RI "int \fBselect_end\fP"
.br
.ti -1c
.RI "unsigned char \fBmode\fP"
.br
.ti -1c
.RI "unsigned char \fBcursor_at_end_of_line\fP"
.br
.ti -1c
.RI "unsigned char \fBinitialized\fP"
.br
.ti -1c
.RI "unsigned char \fBhas_preferred_x\fP"
.br
.ti -1c
.RI "unsigned char \fBsingle_line\fP"
.br
.ti -1c
.RI "unsigned char \fBactive\fP"
.br
.ti -1c
.RI "unsigned char \fBpadding1\fP"
.br
.ti -1c
.RI "float \fBpreferred_x\fP"
.br
.ti -1c
.RI "struct \fBnk_text_undo_state\fP \fBundo\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char nk_text_edit::active"

.SS "struct \fBnk_clipboard\fP nk_text_edit::clip"

.SS "int nk_text_edit::cursor"

.SS "unsigned char nk_text_edit::cursor_at_end_of_line"

.SS "\fBnk_plugin_filter\fP nk_text_edit::filter"

.SS "unsigned char nk_text_edit::has_preferred_x"

.SS "unsigned char nk_text_edit::initialized"

.SS "unsigned char nk_text_edit::mode"

.SS "unsigned char nk_text_edit::padding1"

.SS "float nk_text_edit::preferred_x"

.SS "struct \fBnk_vec2\fP nk_text_edit::scrollbar"

.SS "int nk_text_edit::select_end"

.SS "int nk_text_edit::select_start"

.SS "unsigned char nk_text_edit::single_line"

.SS "struct \fBnk_str\fP nk_text_edit::string"

.SS "struct \fBnk_text_undo_state\fP nk_text_edit::undo"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
