.TH "nk_user_font" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nk_user_font
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nuklear\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnk_handle\fP \fBuserdata\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "\fBnk_text_width_f\fP \fBwidth\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float nk_user_font::height"

.SS "\fBnk_handle\fP nk_user_font::userdata"

.SS "\fBnk_text_width_f\fP nk_user_font::width"


.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
