.TH "Src/Physics/PhysicsManager.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Physics/PhysicsManager.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MotorEngine/MotorEngineAPI\&.h'\fP
.br
\fC#include 'Utils/Singleton\&.h'\fP
.br
\fC#include 'DebugDrawer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBme::PhysicsManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__PHYSICS_PHYSICSMANAGER\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBShapes\fP { \fBSHAPES_SPHERE\fP, \fBSHAPES_BOX\fP, \fBSHAPES_CYLINDER\fP, \fBSHAPES_CAPSULE\fP }"
.br
.ti -1c
.RI "enum \fBMovementType\fP { \fBMOVEMENT_TYPE_DYNAMIC\fP, \fBMOVEMENT_TYPE_STATIC\fP, \fBMOVEMENT_TYPE_KINEMATIC\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "PhysicsManager & \fBme::physicsManager\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __PHYSICS_PHYSICSMANAGER"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMovementType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMOVEMENT_TYPE_DYNAMIC \fP\fP
.TP
\fB\fIMOVEMENT_TYPE_STATIC \fP\fP
.TP
\fB\fIMOVEMENT_TYPE_KINEMATIC \fP\fP
.SS "enum \fBShapes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISHAPES_SPHERE \fP\fP
.TP
\fB\fISHAPES_BOX \fP\fP
.TP
\fB\fISHAPES_CYLINDER \fP\fP
.TP
\fB\fISHAPES_CAPSULE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
