.TH "Src/EntityComponent/SceneManager.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/EntityComponent/SceneManager.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MotorEngine/MotorEngineAPI\&.h'\fP
.br
\fC#include 'Utils/Singleton\&.h'\fP
.br
\fC#include 'InfoScene\&.h'\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBme::SceneManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__ENTITYCOMPONENT_SCENE_MANAGER\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "SceneManager & \fBme::sceneManager\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __ENTITYCOMPONENT_SCENE_MANAGER"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
