.TH "Src/Audio/SoundManager.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Audio/SoundManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include 'MotorEngine/MotorEngineAPI\&.h'\fP
.br
\fC#include 'Utils/Singleton\&.h'\fP
.br
\fC#include 'Utils/Vector3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBme::SoundManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFMOD\fP"
.br
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_FMOD_SOUND_MANAGER\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBFMOD_MODE\fP"
.br
.ti -1c
.RI "typedef int \fBCHANNEL_NUMBER\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "SoundManager & \fBme::soundManager\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBme::MAX_CHANNELS\fP = 36"
.br
.ti -1c
.RI "const float \fBme::DOPPLER_SCALE\fP = 1"
.br
.ti -1c
.RI "const float \fBme::DISTANCE_FACTOR\fP = 1"
.br
.ti -1c
.RI "const float \fBme::ROLLOFF_SCALE\fP = 1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _FMOD_SOUND_MANAGER"

.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBCHANNEL_NUMBER\fP"

.SS "typedef unsigned int \fBFMOD_MODE\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
