.TH "std" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbasic_ostream\fP"
.br
.ti -1c
.RI "struct \fBchar_traits\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBostream\fP = \fBbasic_ostream\fP< char, \fBchar_traits\fP< char > >"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBstd::ostream\fP = typedef \fBbasic_ostream\fP<char, \fBchar_traits\fP<char> >"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
