.TH "Src/Utils/Vector3.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Utils/Vector3.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MotorEngine/MotorEngineAPI\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBme::Vector3\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBOgre\fP"
.br
.ti -1c
.RI "namespace \fBstd\fP"
.br
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__UTILS_VECTOR3\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBstd::ostream\fP = basic_ostream< char, char_traits< char > >"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __UTILS_VECTOR3"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
