.TH "Src/Utils/Vector2.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Utils/Vector2.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MotorEngine/MotorEngineAPI\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVector2\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__UTILS_VECTOR2\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __UTILS_VECTOR2"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
