.TH "Src/Utils/Vector3.cpp" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Utils/Vector3.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Vector3\&.h'\fP
.br
\fC#include <OgreVector3\&.h>\fP
.br
\fC#include <OgreQuaternion\&.h>\fP
.br
\fC#include <LinearMath/btVector3\&.h>\fP
.br
\fC#include <LinearMath/btQuaternion\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstd::ostream\fP & \fBoperator<<\fP (\fBstd::ostream\fP &os, const \fBVector3\fP &v)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBstd::ostream\fP & operator<< (\fBstd::ostream\fP & os, const \fBVector3\fP & v)"
Returns a formatted string representation of the vector
.PP
\fBParameters\fP
.RS 4
\fIos\fP The output stream to write to 
.br
\fIv\fP The vector to format 
.RE
.PP
\fBReturns\fP
.RS 4
The output stream with the formatted string 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
