.TH "Src/Render/Window.h" 3 "Mon Apr 3 2023" "Version 0.2.1" "MotorEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src/Render/Window.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MotorEngine/MotorEngineAPI\&.h'\fP
.br
\fC#include 'Utils/Singleton\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBme::Window\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBme\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__RENDER_WINDOW\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBSDL_Window\fP \fBSDL_Window\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Window & \fBme::window\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __RENDER_WINDOW"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBSDL_Window\fP \fBSDL_Window\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MotorEngine from the source code\&.
